# Relaxed rules for beginner-friendly contributions
default: true

# Turn off rules that commonly trip up new contributors
MD013: false   # line length
MD041: false   # first line should be a top-level heading
MD034: false   # bare URLs
MD029: false   # ordered list item numbering
MD022: false   # blank lines around headings
MD032: false   # blank lines around lists
MD031: false   # blank lines around fenced code blocks
MD012: false   # allow multiple consecutive blank lines
